apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: vault

  source:
    repoURL: https://github.com/tot19/k8s-gitops.git
    targetRevision: main
    path: vault
    helm:
      releaseName: vault
      valueFiles:
        - values.lab.yaml

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
