global:
  enabled: true

server:
  ha:
    enabled: true
    replicas: 3
    raft:
      enabled: true
      setNodeId: true
  image:
    repository: hashicorp/vault
    tag: "1.21.0"

  affinity: {}

  tolerations: []

  dataStorage:
    enabled: true
    size: 5Gi

  service:
    type: ClusterIP
    port: 8200

ui:
  enabled: true
  serviceType: NodePort
  serviceNodePort: 32000
